### ISSUE TITLE
cdk deploy issue

### ISSUE THREAD

**Issue by samirsayyad** [nwspk/twitter-list-follower#5]
Hi,
I am getting the below error on `cdk deploy`.
would you please replicate it?

`--app is required either in command-line, in cdk.json or in ~/.cdk.json`

**Comment by jonodrew** [comment]
Hi 👋🏻 

Thanks for raising this issue. I've reviewed the README and it looks like I missed a step - there should have been a `cdk bootstrap` step.

Can you try going into the infrastructure folder and then calling `cdk bootstrap` followed by `cdk deploy` ?

Please update this ticket to let me know if it works (or doesn't!)

**Comment by samirsayyad** [comment]
Asked me when I run cdk bootstrap : 
`'**' is not an environment name. Run in app directory to glob or specify an environment name like 'aws://123456789012/us-east-1'.`

I have entered my own instance id: 

` cdk bootstrap aws://*********/eu-west-2^C`

Then I got this :
` ⏳  Bootstrapping environment aws://507898586009/eu-west-2...
 ✅  Environment aws://507898586009/eu-west-2 bootstrapped (no changes).`

and finally when I run `cdk deploy`

I get this 
`--app is required either in command-line, in cdk.json or in ~/.cdk.json`

**Comment by jonodrew** [comment]
Many thanks for coming back with such detail. I've merged a couple of fixes - #7 and #6 . Could you pull the main branch and give it another try?

**Comment by samirsayyad** [comment]
Thanks for fixing some issues, I've tried, still seems to have an issue.
Please have a look at the screenshot, I have gotten after executing `cdk bootstrap`.
![image](https://user-images.githubusercontent.com/11405614/116411683-2f080380-a84b-11eb-9c7f-de39a85092ae.png)

**Comment by jonodrew** [comment]
Hey!

Thanks for the screenshot. In future, could you copy and paste the text in? It's easier for me to read that way.

I think it looks like you've not changed the `runtime/.chalice/example_config.json` supplied with the software. Can you take another look at the [draft README](https://github.com/nwspk/twitter-list-follower/pull/4/files) and make sure you're following all the instructions?

**Comment by samirsayyad** [comment]
Hey, 

Thanks, sure I will share the text, I was reading this 
https://github.com/nwspk/twitter-list-follower/blob/main/README.rst

**Comment by samirsayyad** [comment]
That would be great if you explain to me, what is each line? 
I am totally blind there.
```
{
  "version": "2.0",
  "app_name": "twitter-list-follower",
  "automatic_layer": true,
  "stages": {
    "dev": {
      "environment_variables": {
        "CONSUMER_KEY": "consumer-key", // ??? I think we should get it from Twitter??
        "CONSUMER_SECRET": "consumer-secret", // ???  I think we should get it from Twitter??
        "CALLBACK_URL": "callback-url", // ??? I think we should get it from Twitter??
        "APP_TABLE_NAME": "AppTable", // this going to use Dynamo ?
        "APP_DO_NOW_QUEUE_NAME": "", // 
        "APP_DO_LATER_QUEUE_NAME": ""
      },
      "api_gateway_stage": "api",
      "lambda_functions": {
        "api_handler": {
        }
      }
    }
  }
}

```

**Comment by jonodrew** [comment]
Yes! your `CONSUMER_KEY` should be the key from your twitter app, and likewise your `CONSUMER_SECRET` should be your secret key, also from the twitter app.

the `CALLBACK_URL` is one that you write into your twitter app, and is where users should be redirected to. I'll update the docs around that, as it's more complicated than I realised.

Thank you so much for highlighting these issues!

**Comment by jonodrew** [comment]
I've updated the draft docs (#4 ) to add a bit more explanation of the config file. Let me know how you get on.

**Comment by samirsayyad** [comment]
Please have a look :
`sudo cdk bootstrap aws://*************/eu-west-2 --aws-region=eu-west-2`
```
/usr/lib/python3/dist-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.4) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "app.py", line 6, in <module>
    ChaliceApp(app, 'cdk-list-follower')
  File "/usr/local/lib/python3.7/dist-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/opt/projects/twitter-list-follower/infrastructure/stacks/chaliceapp.py", line 30, in __init__
    'APP_PROCESS_QUEUE_NAME': self.process_queue.queue_name,
  File "/usr/local/lib/python3.7/dist-packages/jsii/_runtime.py", line 83, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/chalice/cdk/construct.py", line 69, in __init__
    self._package_app()
  File "/usr/local/lib/python3.7/dist-packages/chalice/cdk/construct.py", line 89, in _package_app
    chalice_config=self.stage_config,
  File "/usr/local/lib/python3.7/dist-packages/chalice/api/__init__.py", line 24, in package_app
    packager.package_app(config, output_dir, stage)
  File "/usr/local/lib/python3.7/dist-packages/chalice/package.py", line 1235, in package_app
    config, chalice_stage_name)
  File "/usr/local/lib/python3.7/dist-packages/chalice/package.py", line 115, in construct_resources
    config, chalice_stage_name)
  File "/usr/local/lib/python3.7/dist-packages/chalice/deploy/appgraph.py", line 31, in build
    for function in config.chalice_app.pure_lambda_functions:
  File "/usr/local/lib/python3.7/dist-packages/chalice/config.py", line 141, in chalice_app
    app = v()
  File "/usr/local/lib/python3.7/dist-packages/chalice/cli/factory.py", line 277, in load_chalice_app
    app = importlib.import_module('app')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/projects/twitter-list-follower/runtime/app.py", line 11, in <module>
    from chalicelib.utils import queues
  File "/opt/projects/twitter-list-follower/runtime/chalicelib/utils.py", line 5, in <module>
    sqs = boto3.resource('sqs')
  File "/usr/local/lib/python3.7/dist-packages/boto3/__init__.py", line 102, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/boto3/session.py", line 389, in resource
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.7/dist-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.7/dist-packages/botocore/session.py", line 851, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python3.7/dist-packages/botocore/client.py", line 87, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.7/dist-packages/botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.7/dist-packages/botocore/args.py", line 73, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/usr/local/lib/python3.7/dist-packages/botocore/args.py", line 154, in compute_client_args
    s3_config=s3_config,
  File "/usr/local/lib/python3.7/dist-packages/botocore/args.py", line 220, in _compute_endpoint_config
    return self._resolve_endpoint(**resolve_endpoint_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/botocore/args.py", line 303, in _resolve_endpoint
    service_name, region_name, endpoint_url, is_secure)
  File "/usr/local/lib/python3.7/dist-packages/botocore/client.py", line 402, in resolve
    service_name, region_name)
  File "/usr/local/lib/python3.7/dist-packages/botocore/regions.py", line 134, in construct_endpoint
    partition, service_name, region_name)
  File "/usr/local/lib/python3.7/dist-packages/botocore/regions.py", line 148, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
Subprocess exited with error 1
```

and FYI I've configured env by below :

`export AWS_DEFAULT_REGION=eu-west-2`
`export AWS_REGION=eu-west-2`
`sudo cat  ~/.aws/config =====> 
[default]
region = eu-west-2
`

**Comment by jonodrew** [comment]
Good morning!

I'm not sure why you're using `sudo` - I don't think it's in any of the instructions. Can I check you've set up a virtual environment?

I'm also not sure you need to add all those arguments to `cdk bootstrap` - it should read them from your `~/.aws/config`

**Comment by samirsayyad** [comment]
Actually, I just used empty `cdk bootstrap`, not worked.
I was googling and tried those ways, also I've used `sudo` because of a permission error.
Yes, of course, I will share with you in private.

**Comment by jonodrew** [comment]
I think this is fixed. I've updated the documentation in #4 to reflect this conversation and will now close this
